version: '3'

services:
  all-in-one:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: all-in-one
    domainname: all-in-one.local
    volumes:
      - ./project_root:/home/ubuntu/catkin_ws
      - ./env_files/bash_profile:/home/ubuntu/.bashrc
      - ./env_files/vimrc:/home/ubuntu/.vimrc
    ports:
      - "5900:5900"
      - "2222:22"
    environment:
      VNC_PASSWORD: ubuntu
      PASSWORD: ubuntu
      RESOLUTION: 1920x1080